services:
  grafana:
    image: grafana/grafana-enterprise:10.1.1
    container_name: grafana-sentry-datasource
    ports:
      - '3000:3000'
    volumes:
      - grafana-data:/var/lib/grafana    
      - ~/work/grafana/license.jwt:/var/lib/grafana/data/license.jwt 
      - ./:/var/lib/grafana/plugins/grafana-sentry-datasource
      - ./provisioning:/etc/grafana/provisioning
    environment:
      - TERM=linux
      - GF_DEFAULT_APP_MODE=development
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_USERS_VIEWERS_CAN_EDIT=true
      - GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=grafana-sentry-datasource
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_BASIC_ENABLED=false
      - GF_LOG_LEVEL=debug
      - GF_DATAPROXY_LOGGING=true
      - GF_CACHING_ENABLED=true
      - GF_ENTERPRISE_LICENSE_PATH=/var/lib/grafana/data/license.jwt 

volumes:
  grafana-data: {}